stayhome = {"AK": 29.3,
            "AL": 23.8,
            "AR": 24.2,
            "AZ": 34.2,
            "CA": 35.6,
            "CO": 30.9, 
            "CT": 32.6,
            "DC": 40.1, 
            "DE": 31.9,
            "FL": 31.6,
            "GA": 27.8,
            "HI": 30.3,
            "IA": 25.7,
            "ID": 29.1,
            "IL": 30.6,
            "IN": 27.4,
            "KS": 26.4,
            "KY": 26.3,
            "LA": 25.2, 
            "MA": 34.7,
            "MD": 34.6, 
            "ME": 30.5,
            "MI": 28.3, 
            "MN": 30.3,
            "MO": 26.5,
            "MS": 23.0, 
            "MT": 28.8,
            "NC": 28.5,
            "ND": 26.4,
            "NE": 26.1,
            "NH": 31.4,
            "NJ": 33.3,
            "NM": 31.7,
            "NV": 33.8, 
            "NY": 35.4,
            "OH": 27.7,
            "OK": 23.8,
            "OR": 33.1,
            "PA": 30.8, 
            "RI": 32.7,
            "SC": 26.6,
            "SD": 26.1,
            "TN": 26.5,
            "TX": 31.0,
            "UT": 30.2,
            "VA": 31.7, 
            "VT": 32.2,
            "WA": 34.2, 
            "WI": 28.8,
            "WV": 26.7,
            "WY": 28.6}

us_abbr =  np.array(["NY", "NJ", "MA", "MI", "PA", 
                     "CA", "IL", "FL", "LA", "TX", 
                     "CT", "GA", "WA", "MD", "ID", 
                     "CO", "OH", "VA", "TN", "NC",
                     "MO", "AL", "AZ", "WI", "SC",
                     "NV", "MS", "RI", "UT", "OK", "KY",
                     "DC", "DE", "IA", "MN", "OR",
                     "ID", "AR", "KS", "NM", "NH",
                     "PR", "SD", "NE", "VT", "ME",
                     "WV", "HI", "MT", "ND", "AK",
                     "WY", "GU", "VI", "MP", "AS"])
us_beta = []
for state in us_abbr:
    try:
        us_beta.append(1-stayhome[state]/100)
    except:
        us_beta.append(1-0.3)
torch.save(torch.from_numpy(np.array(us_beta)).float(), "us_beta.pt")